### ISSUE TITLE
PHP 7.4 required

### ISSUE THREAD

**Issue by carlcs** [craftcms/azure-blob#1]
### Description

The plugin uses typed properties, so PHP 7.4 is required. It installs fine on PHP 7.2 though. The info in the readme is probably incorrect as well.

> This plugin requires Craft CMS 3.1.5 or later.

### Additional info

- Craft version: 3.6.9
- PHP version: 7.3.7
- Database driver & version: PostgreSQL 11.10
- Plugins & versions:
  - Azure Blob Storage | 1.0.0

**Comment by richardegil** [comment]
I see this is a recent report but any updates on this?

- Craft version 3.6.7
- PHP version 7.3.27
- MySQL 5.6.47.0

**Comment by andris-sevcenko** [comment]
Ah, sorry about that. Definitely should have been PHP 7.2 compatible. Just cut the 1.0.1 release that addresses that.

**Comment by carlcs** [comment]
Thanks @andris-sevcenko
