### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by knynkwl** [craftcms/azure-blob#2]
We are running into this issue when supplying a key. We are able to connect via transmit with the same key.

Error in Craft:
![Screen Shot 2021-04-29 at 10 10 34 AM](https://user-images.githubusercontent.com/4225771/116567574-c0bc5300-a8d5-11eb-9ccb-0cfd30b454ea.png)

Connection with Transmit:
<img width="607" alt="CleanShot 2021-04-29 at 10 17 06@2x" src="https://user-images.githubusercontent.com/4225771/116567748-e6e1f300-a8d5-11eb-9a39-c4cde3b1fcd0.png">

**Comment by knynkwl** [comment]
@brandonkelly @andris-sevcenko we are launching a massive Enterprise Commerce site next week and this is hindering us. Any chance we can get some info on this error?

**Comment by angrybrad** [comment]
@knynkwl where you are setting a key? The plugin's settings only have an option for a connection string. Just tested that and it works fine for me:

![CleanShot 2021-04-29 at 13 38 47@2x](https://user-images.githubusercontent.com/61869/116615521-464cfc80-a8f0-11eb-925d-33a7fb066953.png)

**Comment by knynkwl** [comment]
@angrybrad yeah I am adding it to the connection field. Does this mean that the key is wrong because we are able to connect via transmit with the same string?

![Screen Shot 2021-04-29 at 6 55 06 PM](https://user-images.githubusercontent.com/4225771/116628206-9e99f380-a91c-11eb-8049-0f16a8dc2d62.png)

**Comment by angrybrad** [comment]
You'll want to put in the whole connection string there, not the key. Once you do that, it should work.

![CleanShot 2021-04-29 at 16 24 01@2x](https://user-images.githubusercontent.com/61869/116630041-65a35400-a907-11eb-9bf4-c027e3b4bb6c.png)

**Comment by knynkwl** [comment]
Oh shit ok I'll ask the client for that. They told us it was the connection string :( sorry

**Comment by angrybrad** [comment]
@knynkwl no worries!
