### ISSUE TITLE
Switching from DigitalOcean Spaces -> Azure ParseError

### ISSUE THREAD

**Issue by knynkwl** [craftcms/azure-blob#3]
### Description
I got this error when I switched a couple of volumes from DO Spaces to Azure and ran a sync on my staging env.

![Screen Shot 2021-04-30 at 9 33 22 PM](https://user-images.githubusercontent.com/4225771/116767344-96fe4b80-a9fd-11eb-901b-1e9989d1152e.png)

### Steps to reproduce
1. Change from Spaces to Azure
2. Push change or apply this new sync

### Additional info

- Craft version: 3.6.12.1
- PHP version: 7.4
- Database driver & version:
- Plugins versions: 1.0.0

**Comment by knynkwl** [comment]
Oh, I think this is to do with php 7.4 being required.  https://github.com/craftcms/azure-blob/issues/1

**Comment by andris-sevcenko** [comment]
Ah, sorry about that. Definitely should have been PHP 7.2 compatible. Just cut the 1.0.1 release that addresses that.
