### ISSUE TITLE
Transforms not being built

### ISSUE THREAD

**Issue by knynkwl** [craftcms/azure-blob#4]
@andris-sevcenko Not sure if this is a setting in Azure, or if this is a plugin issue, but we switched over to a client Azure blob (coming from DO Spaces), and it seems like the transforms are not taking. 

I am able to see the original image/url.

This is the code I am generating for an example:
<img width="501" alt="Screen Shot 2021-05-05 at 8 08 19 AM" src="https://user-images.githubusercontent.com/4225771/117138468-0f0b9f00-ad79-11eb-9920-f495c75f2d81.png">

And this is what is outputting:
![Screen Shot 2021-05-05 at 8 08 48 AM](https://user-images.githubusercontent.com/4225771/117138566-31052180-ad79-11eb-8f21-bfcb8e19ce2d.png)

FYI, We are able to upload new images.

### Additional info
- Craft version: 3.6.12.1
- PHP version: 7.4
- Plugins & versions: 1.0.1

**Comment by knynkwl** [comment]
I think this is a setting in Azure, closing for now. Will reopen if we find something different.

**Comment by r-anwar** [comment]
Hi @knynkwl, we are having the same issue with Craft4 and Azure Blob Storage. Were you able to resolve your issue? If so, can you share how you did it?

Reza
